name: Run Tests under OpenSCAD

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name:    Run Tests
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Installs Openscad using apt
      - name: Install OpenSCAD
        run: |
          sudo apt-get update
          sudo apt-get install openscad
          sudo snap install openscad-nightly

      # Runs a set of commands using the runners shell
      - name: Run tests
        run: |
          openscad --version
          openscad -o passed.stl  src/tests/run_all.scad
          openscad-nightly --version
          openscad-nightly -o passed.stl  src/tests/run_all.scad

          mkdir -p target/
          for f in src/polysymmetrica/examples/{basics,truncation}/main_*.scad ; do
            echo "Executing $f at $(date)"
            openscad-nightly -o target/$(basename -s .scad "$f").png "$f"
          done
          ls -l target/
